### ISSUE TITLE
The original fingerprintjs is not maintained

### ISSUE THREAD

**Issue by Valve** [valnub/fingerprintjs2sync#1]
It's maintained. 
3 releases only this year. 35 issues closed this year. Working actively on v3 (new major update).

The fact that we didn't want to create a synchronous version of our library based on your request, doesn't mean the repository is not maintained. 

Any long operations should be asynchronous in JavaScript. Fingerprinting takes a long time, 100-300ms, making it synchronous goes against the async nature of JS.

**Comment by valnub** [comment]
Thanks for pointing out, I fixed my statement in README.md file: https://github.com/valnub/fingerprintjs2sync/blob/master/README.md

**Comment by valnub** [comment]
I'd also like to point out that back then in 2017 - when this fork was created - the original Fingerprintjs indeed was not maintained anymore as the previous owner was looking for someone else to take over. I understand that the repo has a new owner by now which is great!

**Comment by Valve** [comment]
Thanks @valnub !

I was indeed looking for a maintainer in 2017, but in 2019 I quit my job to work full-time on this project and now it's maintained and supported.
